"""sync-mplab — Sync pymaketool sources into the MPLAB X project.

Reads CSRC and INCS from pymake/srcs.mk (generated by pymaketool) and:
  1. Rebuilds <logicalFolder name="SourceFiles"> in
     firmware/<PROJECT>.X/nbproject/configurations.xml.
  2. Updates extra-include-directories in <C32> and <C32CPP> sections.
  3. Deletes Makefile-default.mk to force MPLAB X to regenerate build rules.

Run from the workspace root AFTER `make` has regenerated srcs.mk.
Project name is read from VOLTU_PROJECT_NAME env var (fallback: cwd name).
"""

import os
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

from microchip_devtools._project import project_name

SRCS_MK = Path("pymake/srcs.mk")


def _paths(name: str) -> tuple[Path, Path, Path]:
    mplab_dir = Path(f"firmware/{name}.X")
    return (
        mplab_dir,
        mplab_dir / "nbproject/configurations.xml",
        mplab_dir / "nbproject/Makefile-default.mk",
    )


def parse_srcs_mk(path: Path) -> tuple[list[str], list[str]]:
    if not path.exists():
        print(
            f"ERROR: '{path}' not found. Run 'make' first to generate it.",
            file=sys.stderr,
        )
        sys.exit(1)

    csrc: list[str] = []
    incs: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        m = re.match(r"^(?:CSRC|ASRC|ASSRC)\s*\+=\s*(.+)$", line)
        if m:
            csrc.append(m.group(1).strip())
            continue
        m = re.match(r"^INCS\s*\+=\s*-I(.+)$", line)
        if m:
            incs.append(m.group(1).strip().rstrip("/"))

    return csrc, incs


def to_mplab_rel(workspace_path: str, mplab_project_dir: Path) -> str:
    return os.path.relpath(workspace_path, mplab_project_dir).replace(os.sep, "/")


class FolderNode:
    def __init__(self, name: str) -> None:
        self.name = name
        self.children: dict[str, "FolderNode"] = {}
        self.files: list[str] = []

    def add_file(self, rel_parts: list[str], full_path: str) -> None:
        if len(rel_parts) <= 1:
            self.files.append(full_path)
        else:
            folder_name = rel_parts[0]
            if folder_name not in self.children:
                self.children[folder_name] = FolderNode(folder_name)
            self.children[folder_name].add_file(rel_parts[1:], full_path)

    def to_xml(self, parent: ET.Element) -> None:
        for child_name in sorted(self.children):
            folder_el = ET.SubElement(
                parent,
                "logicalFolder",
                {
                    "name": child_name,
                    "displayName": child_name,
                    "projectFiles": "true",
                },
            )
            self.children[child_name].to_xml(folder_el)

        for file_path in sorted(self.files):
            item_el = ET.SubElement(parent, "itemPath")
            item_el.text = file_path


def build_source_tree(csrc_paths: list[str], mplab_project_dir: Path) -> FolderNode:
    root = FolderNode("SourceFiles")

    for ws_path in csrc_paths:
        mplab_path = to_mplab_rel(ws_path, mplab_project_dir)
        parts = mplab_path.split("/")

        i = 0
        while i < len(parts) and parts[i] == "..":
            i += 1
        rel_parts = parts[i:]

        if len(rel_parts) <= 1:
            root.files.append(mplab_path)
        else:
            root.add_file(rel_parts, mplab_path)

    return root


def update_source_files(xml_root: ET.Element, source_tree: FolderNode) -> None:
    root_folder = xml_root.find(".//logicalFolder[@name='root']")
    if root_folder is None:
        print(
            "ERROR: Could not find <logicalFolder name='root'> in XML.",
            file=sys.stderr,
        )
        sys.exit(1)

    source_folder = root_folder.find("logicalFolder[@name='SourceFiles']")
    if source_folder is None:
        print(
            "ERROR: Could not find <logicalFolder name='SourceFiles'> in XML.",
            file=sys.stderr,
        )
        sys.exit(1)

    source_folder.clear()
    source_folder.set("name", "SourceFiles")
    source_folder.set("displayName", "Source Files")
    source_folder.set("projectFiles", "true")
    source_tree.to_xml(source_folder)


def update_include_dirs(
    xml_root: ET.Element, inc_dirs: list[str], mplab_project_dir: Path
) -> None:
    mplab_incs = sorted({to_mplab_rel(d, mplab_project_dir) for d in inc_dirs})
    value = ";".join(mplab_incs)

    for tag in ("C32", "C32CPP"):
        for section in xml_root.iter(tag):
            for prop in section.findall("property[@key='extra-include-directories']"):
                prop.set("value", value)


def _serialize_element(el: ET.Element, depth: int, indent: str = "  ") -> list[str]:
    """Serialize an XML element with MPLAB X-compatible attribute formatting.

    MPLAB X wraps attributes onto separate lines (aligned to first-attr column)
    when the full single-line tag would exceed 80 characters.
    """
    base = indent * depth
    tag = el.tag
    attr_pairs = [f'{k}="{v}"' for k, v in el.attrib.items()]

    has_children = len(el) > 0
    has_text = bool(el.text and el.text.strip())
    self_close = not has_children and not has_text

    close_char = "/>" if self_close else ">"

    if not attr_pairs:
        open_tag = f"{base}<{tag}{close_char}"
    elif len(attr_pairs) == 1:
        open_tag = f"{base}<{tag} {attr_pairs[0]}{close_char}"
    else:
        single_line = f"{base}<{tag} {' '.join(attr_pairs)}{close_char}"
        if len(single_line) <= 80:
            open_tag = single_line
        else:
            cont = " " * (len(base) + len(tag) + 2)  # align to first attr
            first, *rest = attr_pairs
            lines_parts = [f"{base}<{tag} {first}"]
            for attr in rest[:-1]:
                lines_parts.append(f"{cont}{attr}")
            lines_parts.append(f"{cont}{rest[-1]}{close_char}")
            open_tag = "\n".join(lines_parts)

    lines: list[str] = []

    if self_close:
        lines.append(open_tag)
        return lines

    if has_text and not has_children:
        lines.append(f"{open_tag}{(el.text or '').strip()}</{tag}>")
        return lines

    lines.append(open_tag)
    for child in el:
        lines.extend(_serialize_element(child, depth + 1, indent))
    lines.append(f"{base}</{tag}>")
    return lines


def write_xml(tree: ET.ElementTree, path: Path) -> None:
    root = tree.getroot()
    assert root is not None
    lines = _serialize_element(root, depth=0)
    path.write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n' + "\n".join(lines) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    name = project_name()
    mplab_project_dir, configurations_xml, makefile_default_mk = _paths(name)

    if not configurations_xml.exists():
        print(
            f"ERROR: '{configurations_xml}' not found. "
            "Run this script from the workspace root.",
            file=sys.stderr,
        )
        sys.exit(1)

    csrc_paths, inc_dirs = parse_srcs_mk(SRCS_MK)

    tree = ET.parse(configurations_xml)
    xml_root = tree.getroot()

    source_tree = build_source_tree(csrc_paths, mplab_project_dir)
    update_source_files(xml_root, source_tree)
    update_include_dirs(xml_root, inc_dirs, mplab_project_dir)
    write_xml(tree, configurations_xml)

    if makefile_default_mk.exists():
        makefile_default_mk.unlink()


if __name__ == "__main__":
    main()
