"""sync-mplab — Sync pymaketool sources into the MPLAB X project.

Reads CSRC, INCS and SKIP_PATTERNS from pymake/srcs.mk (generated by pymaketool) and:
  1. Rebuilds <logicalFolder name="SourceFiles"> in
     firmware/<PROJECT>.X/nbproject/configurations.xml.
  2. Rebuilds <logicalFolder name="HeaderFiles"> from the .h files discovered by
     scanning the INCS dirs (deepest-first, no duplicates, honoring SKIP_PATTERNS).
  3. Updates extra-include-directories in <C32> and <C32CPP> sections.
  4. Deletes Makefile-default.mk to force MPLAB X to regenerate build rules.

Use --dry-run to preview the source/header changes without writing anything.

Run from the workspace root AFTER `make` has regenerated srcs.mk.
Project name is read from VOLTU_PROJECT_NAME env var (fallback: cwd name).
"""

import argparse
import fnmatch
import os
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

from rich.console import Console

from microchip_devtools._project import project_name

console = Console()

SRCS_MK = Path("pymake/srcs.mk")


def _paths(name: str) -> tuple[Path, Path, Path]:
    mplab_dir = Path(f"firmware/{name}.X")
    return (
        mplab_dir,
        mplab_dir / "nbproject/configurations.xml",
        mplab_dir / "nbproject/Makefile-default.mk",
    )


def parse_srcs_mk(path: Path) -> tuple[list[str], list[str], list[str]]:
    if not path.exists():
        print(
            f"ERROR: '{path}' not found. Run 'make' first to generate it.",
            file=sys.stderr,
        )
        sys.exit(1)

    csrc: list[str] = []
    incs: list[str] = []
    skip_patterns: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        m = re.match(r"^(?:CSRC|ASRC|ASSRC)\s*\+=\s*(.+)$", line)
        if m:
            csrc.append(m.group(1).strip())
            continue
        m = re.match(r"^INCS\s*\+=\s*-I(.+)$", line)
        if m:
            incs.append(m.group(1).strip().rstrip("/"))
            continue
        m = re.match(r"^SKIP_PATTERNS\s*\+=\s*(.+)$", line)
        if m:
            skip_patterns.append(m.group(1).strip().rstrip("/"))

    return csrc, incs, skip_patterns


def _matches_skip(rel_path: str, skip_patterns: list[str]) -> bool:
    return any(fnmatch.fnmatch(rel_path, pat) for pat in skip_patterns)


def discover_headers(
    inc_dirs: list[str],
    skip_patterns: list[str],
    workspace_root: Path,
) -> list[str]:
    """Find every .h under the INCS dirs, deepest-first, deduped, honoring SKIP_PATTERNS.

    Each INCS entry already IS the folder holding headers — scanned directly. Deeper
    dirs are walked first; once a dir is walked it is recorded so a shallower INCS dir
    that contains it skips that subtree (no duplicate headers). SKIP_PATTERNS (fnmatch
    vs the full workspace-relative path) prune both dirs and files.
    """
    roots = []
    seen_roots: set[str] = set()
    for d in inc_dirs:
        rel = os.path.normpath(d)
        if rel in seen_roots:
            continue
        seen_roots.add(rel)
        if _matches_skip(d, skip_patterns):
            continue
        if (workspace_root / d).is_dir():
            roots.append(d)

    # Deepest-first: more path segments = deeper. Lexical tiebreak for determinism.
    roots.sort(key=lambda d: (-d.count("/"), d))

    # Normalized dir paths claimed by already-completed (deeper) root walks. Used
    # to prune subtrees so a shallower root does not re-emit a deeper root's headers.
    processed: set[str] = set()
    headers: list[str] = []

    for root in roots:
        visited: list[str] = []
        for dirpath, dirnames, filenames in os.walk(workspace_root / root):
            cur_rel = os.path.normpath(
                os.path.relpath(dirpath, workspace_root)
            ).replace(os.sep, "/")

            # Prune subdirs: claimed by a deeper root, or SKIP-matched.
            kept = []
            for name in dirnames:
                child_rel = f"{cur_rel}/{name}" if cur_rel != "." else name
                if _matches_skip(child_rel, skip_patterns):
                    continue
                norm = os.path.normpath(child_rel)
                if norm in processed:
                    continue
                kept.append(name)
            dirnames[:] = kept

            visited.append(os.path.normpath(cur_rel))

            for fname in filenames:
                if not fname.endswith(".h"):
                    continue
                file_rel = f"{cur_rel}/{fname}" if cur_rel != "." else fname
                if _matches_skip(file_rel, skip_patterns):
                    continue
                headers.append(file_rel)

        processed.update(visited)

    return headers


def to_mplab_rel(workspace_path: str, mplab_project_dir: Path) -> str:
    return os.path.relpath(workspace_path, mplab_project_dir).replace(os.sep, "/")


class FolderNode:
    def __init__(self, name: str) -> None:
        self.name = name
        self.children: dict[str, "FolderNode"] = {}
        self.files: list[str] = []
        # mixed insertion order: ("file", path) | ("folder", name)
        self._order: list[tuple[str, str]] = []

    def add_file(self, rel_parts: list[str], full_path: str) -> None:
        if len(rel_parts) <= 1:
            self.files.append(full_path)
            self._order.append(("file", full_path))
        else:
            folder_name = rel_parts[0]
            if folder_name not in self.children:
                self.children[folder_name] = FolderNode(folder_name)
                self._order.append(("folder", folder_name))
            self.children[folder_name].add_file(rel_parts[1:], full_path)

    def to_xml(self, parent: ET.Element, sort: bool = True) -> None:
        if sort:
            for child_name in sorted(self.children):
                folder_el = ET.SubElement(
                    parent,
                    "logicalFolder",
                    {
                        "name": child_name,
                        "displayName": child_name,
                        "projectFiles": "true",
                    },
                )
                self.children[child_name].to_xml(folder_el, sort=True)
            for file_path in sorted(self.files):
                item_el = ET.SubElement(parent, "itemPath")
                item_el.text = file_path
        else:
            for kind, value in self._order:
                if kind == "folder":
                    folder_el = ET.SubElement(
                        parent,
                        "logicalFolder",
                        {
                            "name": value,
                            "displayName": value,
                            "projectFiles": "true",
                        },
                    )
                    self.children[value].to_xml(folder_el, sort=False)
                else:
                    item_el = ET.SubElement(parent, "itemPath")
                    item_el.text = value

    def item_paths(self) -> list[str]:
        """All leaf itemPath strings under this node (recursive)."""
        paths = list(self.files)
        for child in self.children.values():
            paths.extend(child.item_paths())
        return paths


def build_tree(
    ws_paths: list[str], mplab_project_dir: Path, root_name: str
) -> FolderNode:
    root = FolderNode(root_name)

    for ws_path in ws_paths:
        mplab_path = to_mplab_rel(ws_path, mplab_project_dir)
        parts = mplab_path.split("/")

        i = 0
        while i < len(parts) and parts[i] == "..":
            i += 1
        rel_parts = parts[i:]

        root.add_file(rel_parts if len(rel_parts) > 1 else [mplab_path], mplab_path)

    return root


def build_source_tree(csrc_paths: list[str], mplab_project_dir: Path) -> FolderNode:
    return build_tree(csrc_paths, mplab_project_dir, "SourceFiles")


def _rebuild_logical_folder(
    xml_root: ET.Element,
    folder_name: str,
    display_name: str,
    tree: FolderNode,
    sort: bool,
) -> None:
    root_folder = xml_root.find(".//logicalFolder[@name='root']")
    if root_folder is None:
        print(
            "ERROR: Could not find <logicalFolder name='root'> in XML.",
            file=sys.stderr,
        )
        sys.exit(1)

    folder = root_folder.find(f"logicalFolder[@name='{folder_name}']")
    if folder is None:
        print(
            f"ERROR: Could not find <logicalFolder name='{folder_name}'> in XML.",
            file=sys.stderr,
        )
        sys.exit(1)

    folder.clear()
    folder.set("name", folder_name)
    folder.set("displayName", display_name)
    folder.set("projectFiles", "true")
    tree.to_xml(folder, sort=sort)


def update_source_files(
    xml_root: ET.Element, source_tree: FolderNode, sort: bool = True
) -> None:
    _rebuild_logical_folder(
        xml_root, "SourceFiles", "Source Files", source_tree, sort
    )


def update_header_files(
    xml_root: ET.Element, header_tree: FolderNode, sort: bool = True
) -> None:
    _rebuild_logical_folder(
        xml_root, "HeaderFiles", "Header Files", header_tree, sort
    )


def update_include_dirs(
    xml_root: ET.Element,
    inc_dirs: list[str],
    mplab_project_dir: Path,
    sort: bool = True,
) -> None:
    rels = [to_mplab_rel(d, mplab_project_dir) for d in dict.fromkeys(inc_dirs)]
    mplab_incs = sorted(rels) if sort else rels
    value = ";".join(mplab_incs)

    for tag in ("C32", "C32CPP"):
        for section in xml_root.iter(tag):
            prop = section.find("property[@key='extra-include-directories']")
            if prop is None:
                prop = ET.SubElement(section, "property")
                prop.set("key", "extra-include-directories")
            prop.set("value", value)


def existing_item_paths(xml_root: ET.Element, folder_name: str) -> set[str]:
    """All <itemPath> texts under logicalFolder[@name=folder_name] (recursive)."""
    folder = xml_root.find(f".//logicalFolder[@name='{folder_name}']")
    if folder is None:
        return set()
    return {el.text for el in folder.iter("itemPath") if el.text}


def _print_diff(label: str, folder_name: str, tree: FolderNode, xml_root) -> None:
    computed = set(tree.item_paths())
    existing = existing_item_paths(xml_root, folder_name)
    added = sorted(computed - existing)
    removed = sorted(existing - computed)

    console.print(
        f"\n[bold]{label}[/bold] "
        f"({len(computed)} total, [green]{len(added)} new[/green], "
        f"[red]{len(removed)} removed[/red])"
    )
    for path in added:
        console.print(f"  [green]+ {path}[/green]")
    for path in removed:
        console.print(f"  [red]- {path}[/red]")


def print_dry_run(
    xml_root: ET.Element, source_tree: FolderNode, header_tree: FolderNode
) -> None:
    console.print("[yellow]⚠ DRY RUN[/yellow] — no files will be modified.")
    _print_diff("Source Files", "SourceFiles", source_tree, xml_root)
    _print_diff("Header Files", "HeaderFiles", header_tree, xml_root)


def _serialize_element(el: ET.Element, depth: int, indent: str = "  ") -> list[str]:
    """Serialize an XML element with MPLAB X-compatible attribute formatting.

    MPLAB X wraps attributes onto separate lines (aligned to first-attr column)
    when the full single-line tag would exceed 80 characters.
    """
    base = indent * depth
    tag = el.tag
    attr_pairs = [f'{k}="{v}"' for k, v in el.attrib.items()]

    has_children = len(el) > 0
    has_text = bool(el.text and el.text.strip())
    self_close = not has_children and not has_text

    close_char = "/>" if self_close else ">"

    if not attr_pairs:
        open_tag = f"{base}<{tag}{close_char}"
    elif len(attr_pairs) == 1:
        open_tag = f"{base}<{tag} {attr_pairs[0]}{close_char}"
    else:
        single_line = f"{base}<{tag} {' '.join(attr_pairs)}{close_char}"
        if len(single_line) <= 80:
            open_tag = single_line
        else:
            cont = " " * (len(base) + len(tag) + 2)  # align to first attr
            first, *rest = attr_pairs
            lines_parts = [f"{base}<{tag} {first}"]
            for attr in rest[:-1]:
                lines_parts.append(f"{cont}{attr}")
            lines_parts.append(f"{cont}{rest[-1]}{close_char}")
            open_tag = "\n".join(lines_parts)

    lines: list[str] = []

    if self_close:
        lines.append(open_tag)
        return lines

    if has_text and not has_children:
        lines.append(f"{open_tag}{(el.text or '').strip()}</{tag}>")
        return lines

    lines.append(open_tag)
    for child in el:
        lines.extend(_serialize_element(child, depth + 1, indent))
    lines.append(f"{base}</{tag}>")
    return lines


def write_xml(tree: ET.ElementTree, path: Path) -> None:
    root = tree.getroot()
    assert root is not None
    lines = _serialize_element(root, depth=0)
    path.write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n' + "\n".join(lines) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Sync pymaketool sources into MPLAB X project."
    )
    parser.add_argument(
        "--preserve-order",
        action="store_true",
        help=(
            "Keep source files in the same order as srcs.mk "
            "instead of sorting alphabetically."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "Print the source/header files and which ones would be added to "
            "configurations.xml, without modifying any file."
        ),
    )
    args = parser.parse_args()
    sort = not args.preserve_order

    name = project_name()
    mplab_project_dir, configurations_xml, makefile_default_mk = _paths(name)

    if not configurations_xml.exists():
        print(
            f"ERROR: '{configurations_xml}' not found. "
            "Run this script from the workspace root.",
            file=sys.stderr,
        )
        sys.exit(1)

    csrc_paths, inc_dirs, skip_patterns = parse_srcs_mk(SRCS_MK)

    tree = ET.parse(configurations_xml)
    xml_root = tree.getroot()

    source_tree = build_tree(csrc_paths, mplab_project_dir, "SourceFiles")
    headers = discover_headers(inc_dirs, skip_patterns, Path("."))
    header_tree = build_tree(headers, mplab_project_dir, "HeaderFiles")

    if args.dry_run:
        print_dry_run(xml_root, source_tree, header_tree)
        return

    update_source_files(xml_root, source_tree, sort=sort)
    update_header_files(xml_root, header_tree, sort=sort)
    update_include_dirs(xml_root, inc_dirs, mplab_project_dir, sort=sort)
    write_xml(tree, configurations_xml)

    if makefile_default_mk.exists():
        makefile_default_mk.unlink()


if __name__ == "__main__":
    main()
